export class OrderItemProduct {
  id: number;
  orderId: number;
  productId: number;
  productVersion: string;
  productSaleSpecId: number;
  productName: string;
  productsalespec: string;
  salespecquantity: number;
  sellunit: string;
  productspec: string;
  specquantity: number;
  packagename: string;
  unitname: string;
  salemode: number;
  isusebonus: boolean;
  isusecoupon: boolean;
  iscumulative: boolean;
  isadditionalpurchase: boolean;
  supplierid: number;
  isregionpurchaseproduct: boolean;
  oldproductid: number;
  productbusinessclass: number;
  isinordergive: boolean;
  ishiddenproduct: boolean;
  lastModifyTime: string;
  productinfoid: number;
  productspecid: number;
}
